### ISSUE TITLE
Packaging for Alpine Linux - build failures on s390x and ppc64le

### ISSUE THREAD

**Issue by sodface** [tari01/odio-edit#1]
Hello, thank you for the cool software! I submitted packages for Alpine Linux, for both libodiosacd and odio-edit. The libodiosacd has been merged into the testing repository and builds on all supported arches:  

[Alpine libodiosacd package](https://pkgs.alpinelinux.org/packages?name=libodiosacd&branch=edge)

The odio-edit package has also been merged but I had to disable building for s390x and ppc64le. 

[Alpine odio-edit package](https://pkgs.alpinelinux.org/packages?name=odio-edit&branch=edge)

The full build logs can be viewed [here](https://gitlab.alpinelinux.org/sodface/aports/-/pipelines/126947) but here are excerpts from each:

s390x:

```
src/gstreamer.c: In function 'gstbase_GetAudioFormat':
src/gstreamer.c:178:9: error: duplicate case value
  178 |         case GST_AUDIO_FORMAT_F32:
      |         ^~~~
src/gstreamer.c:175:9: note: previously used here
  175 |         case GST_AUDIO_FORMAT_F32BE:
      |         ^~~~
src/gstreamer.c:187:9: error: duplicate case value
  187 |         case GST_AUDIO_FORMAT_S16:
      |         ^~~~
src/gstreamer.c:184:9: note: previously used here
  184 |         case GST_AUDIO_FORMAT_S16BE:
      |         ^~~~
src/gstreamer.c:194:9: error: duplicate case value
  194 |         case GST_AUDIO_FORMAT_S32:
      |         ^~~~
src/gstreamer.c:191:9: note: previously used here
  191 |         case GST_AUDIO_FORMAT_S32BE:
      |         ^~~~
src/gstreamer.c:213:9: error: duplicate case value
  213 |         case GST_AUDIO_FORMAT_S24:
      |         ^~~~
src/gstreamer.c:202:9: note: previously used here
  202 |         case GST_AUDIO_FORMAT_S24BE:
      |         ^~~~
```

ppc64le:

```
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadDsdFrame'
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadSegmentData'
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadMappingData'
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadProbabilityTables'
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadArithmeticCodedData'
/usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../powerpc64le-alpine-linux-musl/bin/ld: /usr/lib/gcc/powerpc64le-alpine-linux-musl/11.2.1/../../../../lib/libodiosacd.so: undefined reference to `framereader_ReadFilterCoefSets'
collect2: error: ld returned 1 exit status
make: *** [Makefile:27: odio-edit] Error 1
```

**Comment by tari01** [comment]
@sodface 

Looking at https://gitlab.alpinelinux.org/sodface/aports/-/pipelines/126947, is seems that `build-s390x` does not fail?

About ppc64le: I cannot test it right now, but it looks like the `libodiosacd` build is messed up, not `odio-edit`. Can you check if the library is properly built and available/found by the linker?

**Comment by sodface** [comment]
My apologies, I linked to the wrong pipeline job, s390x and ppc64le both fail on:
https://gitlab.alpinelinux.org/sodface/aports/-/pipelines/126944

s390x passed on 126947 because I disabled it in the APKBUILD file. If you click on the green checkmark you get the detailed build log:
https://gitlab.alpinelinux.org/sodface/aports/-/jobs/758074

Part of the output is:

```
### Build summary ###
>>> testing/odio-edit: disabled for s390x
>>> No packages found to be built.
```

I guess it setups up the build, finds nothing to do, then marks it a success, which is a little misleading. Do nothing, successfully, as they say.

I will look at the ppc64le you mentioned though I don't have any hardware to test with.

**Comment by sodface** [comment]
I just re-ran ppc64le and it passed the CI/CD now:
https://gitlab.alpinelinux.org/sodface/aports/-/jobs/759322

I will try the s390x again also.

**Comment by tari01** [comment]
> I just re-ran ppc64le and it passed the CI/CD now: https://gitlab.alpinelinux.org/sodface/aports/-/jobs/759322

Yay!

> I will try the s390x again also.

That one will fail because of some GStreamer definitions. I'll create a draft PR with a fix and ping you to test it.

**Comment by sodface** [comment]
Yes, s390x did fail again:
https://gitlab.alpinelinux.org/sodface/aports/-/pipelines/127124

Incidentally, maybe a different topic, but I had to specify `gst-plugins-good` as a run-time dependency otherwise odio-edit would build and start ok but as soon as I attempted to open a .wav file the window would freeze and I had to kill the process. I didn't see `gst-plugins-good` listed as a dependency in your documentation which is why I didn't include it in my early build attempts. Adding it definitely fixed the freeze when opening .wav files but maybe it wasn't specifically `gst-plugins-good` but something else it pulled in? 

```
depends="dconf gst-libav gst-plugins-good"
```

**Comment by tari01** [comment]
> Incidentally, maybe a different topic, but I had to specify `gst-plugins-good` as a run-time dependency otherwise odio-edit would build and start ok but as soon as I attempted to open a .wav file the window would freeze and I had to kill the process. I didn't see `gst-plugins-good` listed as a dependency in your documentation which is why I didn't include it in my early build attempts. Adding it definitely fixed the freeze when opening .wav files but maybe it wasn't specifically `gst-plugins-good` but something else it pulled in?
> 
> ```
> depends="dconf gst-libav gst-plugins-good"
> ```

In my world (Manjaro), gst-plugins-good is always preinstalled, so it escaped me. You are right, it is a runtime dependency. Also, I am changing odio-edit to depend on all 3 plugins - we want it to handle any format without nasty surprises. Please depend on:

`gst-plugins-good gst-plugins-bad gst-plugins-ugly`

**Comment by tari01** [comment]
After some tinkering, it turned out to be simpler to simply commit the changes rather than creating a PR. Can I ask you to try to build the latest Git code? If it builds on all architectures, I will make a release. Thanks.

**Comment by sodface** [comment]
Ok, looks good!

https://gitlab.alpinelinux.org/sodface/aports/-/pipelines/127139

**Comment by tari01** [comment]
Excellent.

Bug No. 1 resolved by https://github.com/tari01/odio-edit/commit/e91dba4f187bf7ae22489a5d6c0a02d3d179c512
Bug No. 2 resolved by unknown magic.

Release 22.7.5 is out. Closing.
