### ISSUE TITLE
Settings schema 'in.tari.odio-edit' is not installed

### ISSUE THREAD

**Issue by linamist** [tari01/odio-edit#4]
After successfully building and installing release 24.1.1, when running odio-edit I get the following:

```
$ odio-edit 

(odio-edit:327959): GLib-GIO-ERROR **: 23:14:59.018: Settings schema 'in.tari.odio-edit' is not installed
Trace/breakpoint trap (core dumped)
```

Any ideas?

**Comment by tari01** [comment]
You will probably need to run

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas`

to update the schema cache.

**Comment by linamist** [comment]
Yeah! This did the trick! Thank you!
